### PR TITLE
Ft landing page 162979605

### PR DESCRIPTION
**Pull request by Sulwe**
**What this PR does**
Creates the homepage

**Description of task**

1.   A user friendly uncrowded homepage
2.  A responsive page
3.  Provides a navigation bar to other sections
4.  Allows a user to view available meetups to join or create their own meetups
5.  Provides links for login and sign up

**Manual testing**
Clone the repo and open the index.html file with a web browser of your choice

**Relevant Pivotal Tracker Stories**
#162979605

**Screenshots**
pr3

### CODE REVIEW

**Comment by wachiranduati** [comment]
Amazing....love the design

**Comment by wachiranduati** [comment]
merged into the wrong branch tho

**Comment by SolomonMacharia** [comment]
Nice UI

**Comment by SolomonMacharia** [comment]
lovely UI.

**Pull request merged**
